### ISSUE TITLE
#addToBasket is not the only way to add to the basket

### ISSUE THREAD

**Issue by jtlapp** [RobertSpread/spreadcart#16]
Sometimes SpreadShop uses the element at #addToBasket to add an element to the basket, and sometimes it's using something else. The spreadCart plugin therefore sometimes does not update.

I'm thinking that a more reliable approach is to set a timer that periodically counts the items in the cart and updates #spreadCartIcon.

**Comment by jtlapp** [comment]
Never mind. This is a bug I introduced. Will check in a fix shortly.

**Comment by RobertSpread** [comment]
I also thought on pulling every 2 seconds or so to prevent that we need to rely on #addToBasket.
This would also prevent that this plugin breaks when the dev change the ID.
We could do both but I think, ig you introduced the bug and you can fix it ;) , that ot should maybe a lower priority.

**Comment by RobertSpread** [comment]
Should we close this topic for now?

**Comment by jtlapp** [comment]
Oh yeah. My last push included a fix. Thanks.
