### ISSUE TITLE
SpreadShop must be in every page that shows spreadcart

### ISSUE THREAD

**Issue by jtlapp** [RobertSpread/spreadcart#17]
Because spreadcart reads a local storage structure that SpreadShop produces, the spreadcart shopping cart can only be displayed on web pages that include an instance of SpreadShop. I want the shopping cart in the menu bar of all of my pages, so I have to include SpreadShop on all of my pages. Fortunately, things still work if you hide (display:none) the shop. But this makes every single page work harder to load, and it works the SpreadShirt API harder than is necessary.

I'm thinking we need a pure-API solution, assuming we can access the cookies of SpreadShirt.com from our own domain -- which I believe is NOT allowed.

So it seems that if you're going to do a shopping cart properly, you have to implement both the store and the cart from the same web site. You can't mix one site's cart with another site's script.

**Comment by RobertSpread** [comment]
Hi there,

The spreadcart originally read from the localstorage and was running on any page of the same domain. There should be no issue at all with that.

**Comment by jtlapp** [comment]
Okay, but some of the basket data is null without the shopping cart, causing errors. The nulls went away by including the shopping cart. The data is certainly null on the first load, before a shop has ever been pulled up by the browser, but data is also sometimes null even when there's something in the cart according to other pages. I'll have to investigate further why basket data is sometimes null without SpreadShop.

**Comment by jtlapp** [comment]
I think it was apiBasketId. That may sometimes go null. Does a basket ever get reset or become invalid?

**Comment by RobertSpread** [comment]
Ah, ok, now I get the problem.
When the shop is loaded there will be a basket created. So, you  will never have a non existing basket.
What we would need to do to prevent this, is to handle the case when the localStorage is empty.
Otherwise a basket becomes only invalid when it is moved to the order state

**Comment by jtlapp** [comment]
Yes, that's one of the problems. Perhaps I confused myself having multiple windows open with some reporting items in a basket and some reporting errors.

**Comment by jtlapp** [comment]
Also, the checkout button has a link that includes the basket ID, so we can't build that button until after the shop has loaded; but if we're not loading a shop, we never get the ID to build the button. It seems that we have to defer building the popup cart until after we know we have a basket, but we have to construct the spreadcart icon no matter what.

**Comment by jtlapp** [comment]
Let me check in the latest, so we're working from the same stuff. I'll do that now.

**Comment by RobertSpread** [comment]
perfect!

**Comment by jtlapp** [comment]
I'm tweaking it before checking it in. Before we've ever loaded a shopping cart, we can't build the checkout button, and yet we should be able to display the basket-empty message.

**Comment by jtlapp** [comment]
It appears that the basket sometimes gets reset, and when it does, basketData is non-null, yet basketData.apiBasketId is undefined. If I decline to build the popup cart until it is defined, things seem to work fine.

**Comment by jtlapp** [comment]
Okay, it looks like you're right. I don't need to load SpreadShop on every page. However, I had to carefully avoid building the "filled" portion of the cart until an apiBasketId became available. Sometimes there's basket data but no apiBasketId. I'm not sure what those circumstances are, but I did encounter it while debugging this fix. Maybe a shop loaded but no item was in the basket yet?

**Comment by RobertSpread** [comment]
This is very likely that this happens since the initial basket is alwys empty.
Let us try to bypass this issue.

**Comment by jtlapp** [comment]
My last pull request seems to handle things well.

**Comment by RobertSpread** [comment]
Do we want to close this ticket?

**Comment by jtlapp** [comment]
Yeah. I suspect that was the problem. Thanks for your help!
