### ISSUE TITLE
Discussion on branches

### ISSUE THREAD

**Issue by RobertSpread** [RobertSpread/spreadcart#19]
I created a new branch and used all data from the last commit of you.
Could you please check if this is all correct? 
If so, I will merge this branch in the master so that we are back on track again

**Comment by jtlapp** [comment]
Yes, revertedChanges is functionally what I committed. Are you running the code through an automatic reformatter? It doesn't handle multi-line statements well. My editor wraps at column 80. To keep everything readable, I indent the second and subsequent lines of a multi-line statement one level farther right than the first line of the statement. Your reformatter has indented all lines of the statement at the same level, making them look like separate statements -- harder to manage the code.

**Comment by RobertSpread** [comment]
Happy to hear that it works now. I will check if I have a reformatter. Honestly, do not know it ;)

**Comment by RobertSpread** [comment]
Merged the reverted commit into master so that we have a master up to date.

**Comment by jtlapp** [comment]
Yah, I was going to suggest that. I have a minor tweak to add but don't want to have to integrate that minor tweak with the quantity-update code yet. I'll do a pull request for that. Thanks!
