### ISSUE TITLE
Shopping cart image links now broken

### ISSUE THREAD

**Issue by jtlapp** [RobertSpread/spreadcart#32]
Hey Robert,

I went to use my site and found that the links to images in the shopping cart no longer work. One gives me this:

http://image.spreadshirtmedia.com/image-server/v1/products/103817177?appearanceId=231

But most give me this:

http://image.spreadshirtmedia.com/image-server/v1/products/103816991?appearanceId=259

This is a pretty urgent issue. I'm not even sure wear to look to address this.

~joe

**Comment by jtlapp** [comment]
Actually, these images now appear to show other people's prints on T-shirts:

http://image.spreadshirtmedia.com/image-server/v1/products/103721409?appearanceId=231

And some are just strange replacements:

http://image.spreadshirt.com/image-server/v1/designs/10429609

**Comment by jtlapp** [comment]
Here's the fix. Spreadshirt changed the kind of product ID that is required to look up an image. We ultimately need spreadshirt publishing and conforming to a published contract made with developers (i.e. an official API) and informing us developers in advance of changes that may break things.

I'll check it in when I get a chance to reconcile any other changes that are waiting. The following code:

```
itemDiv.append('<img style="width:30%" src="'+ plugin.config.mediaURL + basketItem.element.id +'?appearanceId='+  basketItem.element.properties['appearance'] +'"/>');
```

Needs to change to this:

```
itemDiv.append('<img style="width:30%" src="'+ plugin.config.mediaURL + basketItem.element.properties['product'] +'?appearanceId='+  basketItem.element.properties['appearance'] +'"/>');
```

**Comment by RobertSpread** [comment]
I assume this should now be fixed?

**Comment by jtlapp** [comment]
Yes, the fix was in my pull request.
