### ISSUE TITLE
Image colors should ideally match ordered colors

### ISSUE THREAD

**Issue by jtlapp** [RobertSpread/spreadcart#4]
The images displayed in the cart show the color of the display item that the user originally selected, not the color of the item that the user ultimately ordered. However, the text next to each item does properly name the color. This is a potential source of concern or confusion for the user. We can probably live with this for the interim but might ultimately want to display the image in the color ordered.

**Comment by RobertSpread** [comment]
No problem. I will adjust this tonight.

**Comment by jtlapp** [comment]
Oh awesome! I hope it's not too difficult. Thank you!

**Comment by RobertSpread** [comment]
Fixed with the last update.

**Comment by jtlapp** [comment]
Excellent! Thank you!
