### ISSUE TITLE
Deletion of last item leads to unwanted behaviour

### ISSUE THREAD

**Issue by RobertSpread** [RobertSpread/spreadcart#6]
- add item to basket
- delete item from basket
- click continue shopping
- expected behaviour:
  *\* basket closed
- current beahviour
  *\* basket closes
  *\* empty basket

**Comment by RobertSpread** [comment]
I would suggest to have only ne basket represenatation where the content is either "empty basket" or " basket information. With this we have a component less to deal with.

**Comment by jtlapp** [comment]
I hope I didn't create that problem. I can't test at the moment, but will look into the dynamic aspects of the cart today.

**Comment by RobertSpread** [comment]
Unfortunately you did create the issue. But, no biggie at all. I fixed it with the last commit. Took just a couple of minutes.
